### ISSUE TITLE
Any ideas on how to implement this using the Firefox driver?

### ISSUE THREAD

**Issue by medina325** [enrialonso/playwright-auto-select-certificates-for-url#1]
Hi 💯!

I found your repo while searching on how to authenticate with a certificate using playwright. I'm using the Python API and the tricky part is I have to use Firefox instead of Chrome.

Any ideas on where to install the certificates, for the browser to automatically choose them?

**Comment by enrialonso** [comment]
Let me test this on firefox, but can you explain me your use case? @medina325

**Comment by medina325** [comment]
Being very specific, I need to authenticate to [this](https://cav.receita.fazenda.gov.br/autenticacao/login) website, by SSO into another website using a certificate.

![image](https://user-images.githubusercontent.com/56964034/184707279-9220e78c-d85a-4206-9256-77a4d732afd8.png)
![image](https://user-images.githubusercontent.com/56964034/184707435-b84aac23-4a89-44be-8a6e-74309ba0a870.png)

I believe your solution based on autoloading the certificate when required, would fit well for my use case, however I cannot use the Chrome driver since the first website recognizes it as a bot, and blocks it out (even though they say it's perfectly legal to use bots in their website).
By using the Firefox driver I'm able to pass that click, however I'm not able to autoload a certificate, like I'd be if I was using your workaround with the Chrome driver.

**Comment by medina325** [comment]
There is a workaround in javascript apparently, describe [here](https://github.com/microsoft/playwright/issues/1799#issuecomment-959011162), however my implementation needs to be in Python, and I still haven't figured out a way to reproduce that workaround in Python.

**Comment by enrialonso** [comment]
@medina325 One question more, what type of certificate used in this site? PKCS11 or PKCS12? firefox support both but chrome not support PKCS11

**Comment by medina325** [comment]
PKCS12 only

**Comment by enrialonso** [comment]
@medina325 on this PR #2 can you see the first aproach to add support on firefox browser, need:
- Launch first a browser with a persistent context this create the files for a default `profile`
- Update some files like `prefs.js` for set the `about:config` of the browser
- Run a command for store the certificates (PKCS12 only) on the `cert9.db`

With this you can open again the browser completely configured for automatic selection of the certificates, works ok on `badssl.com`, let me know if this approach is near to solve your use case pls!

**Comment by medina325** [comment]
Amazing, I'll give it a shot tomorrow and will let u know!

**Comment by medina325** [comment]
It worked! Absolutely stunned by your help 🥇!

Tell me, anyway to buy you a coffee? This might have been my best open source exp yet :)

**Comment by enrialonso** [comment]
@medina325 jajaja no problem, it's my first contribution also. I am very curious how you apply this for automate your tools on the business, can you speak with me and explain for what use this? 

In a current freelance job we made a similar sing up in the government portal to extract data and give tax solutions our customers, your case is similar?

Can you write me on enrialonso@gmail.com

And now I need write the documentation of this to close de PR jejejeje!
